### PR TITLE
Fix spelling of examples directory name

### PR DESCRIPTION
**Pull request by douglasnaphas**
exmaples -> examples

### CODE REVIEW

**Comment by saidsef** [comment]
:robot: 
Summary of Changes:

1. The directory name "exmaples" has been changed to "examples".
2. The following files have been renamed from "exmaples" to "examples":
   - README.md
   - complete/README.md
   - complete/main.tf
   - complete/outputs.tf
   - complete/terraform.tfvars
   - complete/variables.tf
   - complete/versions.tf
   - remote/README.md
   - remote/main.tf
   - remote/outputs.tf
   - remote/variables.tf
   - remote/versions.tf

Optimizations:
No optimizations are required as this patch only involves renaming directories and files. 

Potential Problems:
There are no potential problems identified in this patch. 

<sub><sub>> gpt-3.5-turbo-16k</sub></sub>

**Comment by saidsef** [comment]
@douglasnaphas Welcome, and thanks for raising the PR.

Could you also please update the paths in CI workflows:

```
.github/workflows/tfsec.yml
```
https://github.com/douglasnaphas/terraform-aws-terraform-cloud-oidc/blob/4408745a2bbda8f1ebfdbb637f50d5a165082404/.github/workflows/tfsec.yaml#L43C12-L43C20

```
.github/workflows/ci.yml
```
https://github.com/douglasnaphas/terraform-aws-terraform-cloud-oidc/blob/4408745a2bbda8f1ebfdbb637f50d5a165082404/.github/workflows/ci.yaml#L53-L62

**Comment by douglasnaphas** [comment]
> @douglasnaphas Welcome, and thanks for raising the PR.
> 
> Could you also please update the paths in CI workflows:
> 
> ```
> .github/workflows/tfsec.yml
> ```
> 
> https://github.com/douglasnaphas/terraform-aws-terraform-cloud-oidc/blob/4408745a2bbda8f1ebfdbb637f50d5a165082404/.github/workflows/tfsec.yaml#L43C12-L43C20
> 
> ```
> .github/workflows/ci.yml
> ```
> 
> https://github.com/douglasnaphas/terraform-aws-terraform-cloud-oidc/blob/4408745a2bbda8f1ebfdbb637f50d5a165082404/.github/workflows/ci.yaml#L53-L62

Done.

**Comment by saidsef** [comment]
:robot: 
Changes in the patch:

1. Spelling correction: The directory name "exmaples" is changed to "examples" in multiple files.
2. File renaming: The files within the "exmaples" directory are renamed to the "examples" directory.

Optimization suggestion:
No optimization is required as the changes are simple spelling corrections and file renaming.

Potential problems:
There are no potential problems identified in the modified lines.

Summary of changes in ascending order of importance:

1. Spelling correction in .github/workflows/tfsec.yaml:
   - "Remote exmaple test" is changed to "Remote example test" in the job name.

2. Spelling correction in .github/workflows/ci.yaml:
   - "Exmaple Complete Validate" is changed to "Example Complete Validate" in the job name.
   - "Exmaple Remote Validate" is changed to "Example Remote Validate" in the job name.

3. Directory and file renaming:
   - The directory "exmaples" is renamed to "examples" in multiple files.
   - The files within the "exmaples" directory are renamed to the "examples" directory.

Example:
Before:
```
- name: Exmaple Complete Validate
```
After:
```
- name: Example Complete Validate
```

Before:
```
- name: Exmaple Remote Validate
```
After:
```
- name: Example Remote Validate
``` 

<sub><sub>> gpt-3.5-turbo-16k</sub></sub>

**Comment by saidsef** [comment]
@douglasnaphas this looks good, will merge it - thanks!

> The failed ci step is a separate issue, will fix that in a different PR.

**Review by saidsef — APPROVED** [review]
LGTM

**Pull request merged**
